USE Tienda;

CREATE TABLE ticket (
    id_compra INT AUTO_INCREMENT PRIMARY KEY,
    id_ticket INT AUTO_INCREMENT PRIMARY KEY
)

CREATE TABLE admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contrasena INT
)